# Generated by Django 4.1.6 on 2023-02-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_room_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='block',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
