# Generated by Django 4.1.6 on 2023-03-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default=-13, max_length=20),
            preserve_default=False,
        ),
    ]
