# Generated by Django 4.1.6 on 2023-02-09 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='Complaint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint'),
            preserve_default=False,
        ),
    ]
